---
- name: Install Docker and Zabbix agent
  hosts: agent
  become: true
  gather_facts: False
  roles:
    - docker
    - zabbix-agent

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

                
        # - name: Install Docker
        #include_role:
        #name: docker
    
        #  - name: Install Zabbix agent    
        #include_role:
        #name: zabbix-agent
