---
- name: Install Docker and Zabbix agent
  hosts: agent
  become: true
  gather_facts: False

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - include_role:
        name: docker

    - include_role:
        name: zabbix-agent
