---
zabbix_agent_packages:
  - zabbix-agent2
zabbix_agent_config_file: /etc/zabbix/zabbix_agentd.conf
zabbix_agent_config_items:
  - { regexp: '^Server=', line: 'Server=zabbix-server.example.com' }
  - { regexp: '^ServerActive=', line: 'ServerActive=zabbix-server.example.com' }
  - { regexp: '^Hostname=', line: 'Hostname={{ ansible_hostname }}' }


# zabbix_agent_server: zabbix-server.example.com
# zabbix_agent_hostname: "{{ ansible_hostname }}"
