- name: Configure Zabbix agent
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^Server=', line: 'Server=zabbix-server.example.com' }
    - { regexp: '^ServerActive=', line: 'ServerActive=zabbix-server.example.com' }
